# CONSOLIDATE DatePrep

In [1]:

#fileloc  = '/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-one/code/Users/karan.bhatti'
fileloc  = '/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-one-8c-32gb/code/Users/karan.bhatti'

import sys
print(sys.path)
print()
#sys.path.append(f'{fileloc}')
print()
#print(sys.path)

['/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-one-8c-32gb/code/Users/karan.bhatti', '/anaconda/envs/azureml_py38/lib/python38.zip', '/anaconda/envs/azureml_py38/lib/python3.8', '/anaconda/envs/azureml_py38/lib/python3.8/lib-dynload', '', '/anaconda/envs/azureml_py38/lib/python3.8/site-packages', '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/_project/vendor', '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/automl/core/_vendor']

In [2]:

class Data(object):
    pass

df = Data
summ = Data

In [3]:
import helpdesk as hd

In [4]:

import pandas as pd, numpy as np
from datetime import datetime

In [5]:

DEBUG = True
seed = 1919

In [6]:

pd.set_option('display.max_rows', 50);
pd.set_option('display.max_columns', 50);
pd.set_option('display.width', 200);

In [7]:
# Import the Base Dataset
base_dataset_name = 'dataset_base_2022-11-19.csv'

df_base_raw = pd.read_csv(f'{fileloc}/{base_dataset_name}')

print(df_base_raw.shape)
print()
print(df_base_raw.columns.values.tolist())

(541552, 21)

['@id_DOG', 'DogName', 'y_runtime', 'RaceId', '@id_RACE', 'Distance', 'RaceGrade', 'Track', 'Event_Dt', 'ft_sp', 'position', 'x_num_dogs', 'Winner_actual', 'Top3_actual', 'position_random', 'Winner_random', 'Top3_random', 'position_fasttrack', 'Winner_fastrack', 'Top3_fastrack', 'y_pos']

In [8]:

print(pd.DataFrame(df_base_raw.isna().sum()).transpose())

   @id_DOG  DogName  y_runtime  RaceId  @id_RACE  Distance  RaceGrade  Track  Event_Dt  ft_sp  position  x_num_dogs  Winner_actual  Top3_actual  position_random  Winner_random  Top3_random  \
0        0        0          0       0         0         0          0      0         0      0         0           0              0            0                0              0            0

   position_fasttrack  Winner_fastrack  Top3_fastrack  y_pos
0                   0                0              0      0

In [9]:
# Import the Speed Profile

speed_profile_name = 'dataprep_speed_profile_2022-10-27.csv'

df_speed_profile = pd.read_csv(f'{fileloc}/{speed_profile_name}')

print(df_speed_profile.shape)
print()
print(df_speed_profile.columns.values.tolist())

(577317, 11)

['@id_DOG', '@id_RACE', 'x_dist', 'x_races_tot', 'x_no_prev_races', 'x_speed_prev', 'x_speed_avg', 'x_speed_min', 'x_speed_max', 'x_speed_range', 'x_speed_std']

In [10]:

print(pd.DataFrame(df_speed_profile.isna().sum()).transpose())

   @id_DOG  @id_RACE  x_dist  x_races_tot  x_no_prev_races  x_speed_prev  x_speed_avg  x_speed_min  x_speed_max  x_speed_range  x_speed_std
0        0         0       0            0                0             0            0            0            0              0            0

In [11]:

# Import the Race Profile
race_profile_name = 'dataprep_raceprofile_2022-10-29.csv'

df_race_profile = pd.read_csv(f'{fileloc}/{race_profile_name}')

print(df_race_profile.shape)
print()
print(df_race_profile.columns.values.tolist())

(541552, 16)

['@id_DOG', '@id_RACE', 'G5', 'G4', 'G3', 'G2', 'G1', 'Gmix', 'Gmas', 'Gmai', 'Gh', 'Gres', 'Gnov', 'Gsp', 'Gfin', 'RaceGrade_H1']

In [12]:

# Merge the datasets together
print(df_base_raw.shape)
print(df_speed_profile.shape)
print(df_race_profile.shape)
print()

df_base0 = pd.merge( df_base_raw, df_speed_profile, on = ['@id_DOG','@id_RACE'], how = 'left')
print(df_base0.shape)    
print(df_base0.columns.values.tolist())    

df_base1 = pd.merge( df_base0, df_race_profile, on = ['@id_DOG','@id_RACE'], how = 'left')
print(df_base1.shape)
print(df_base1.columns.values.tolist())

(541552, 21)
(577317, 11)
(541552, 16)

(541552, 30)
['@id_DOG', 'DogName', 'y_runtime', 'RaceId', '@id_RACE', 'Distance', 'RaceGrade', 'Track', 'Event_Dt', 'ft_sp', 'position', 'x_num_dogs', 'Winner_actual', 'Top3_actual', 'position_random', 'Winner_random', 'Top3_random', 'position_fasttrack', 'Winner_fastrack', 'Top3_fastrack', 'y_pos', 'x_dist', 'x_races_tot', 'x_no_prev_races', 'x_speed_prev', 'x_speed_avg', 'x_speed_min', 'x_speed_max', 'x_speed_range', 'x_speed_std']
(541552, 44)
['@id_DOG', 'DogName', 'y_runtime', 'RaceId', '@id_RACE', 'Distance', 'RaceGrade', 'Track', 'Event_Dt', 'ft_sp', 'position', 'x_num_dogs', 'Winner_actual', 'Top3_actual', 'position_random', 'Winner_random', 'Top3_random', 'position_fasttrack', 'Winner_fastrack', 'Top3_fastrack', 'y_pos', 'x_dist', 'x_races_tot', 'x_no_prev_races', 'x_speed_prev', 'x_speed_avg', 'x_speed_min', 'x_speed_max', 'x_speed_range', 'x_speed_std', 'G5', 'G4', 'G3', 'G2', 'G1', 'Gmix', 'Gmas', 'Gmai', 'Gh', 'Gres', 'Gnov', 'Gsp', 'Gfin', 'RaceGrade_H1']

In [13]:

print(pd.DataFrame(df_base1.isna().sum()).transpose())

   @id_DOG  DogName  y_runtime  RaceId  @id_RACE  Distance  RaceGrade  Track  Event_Dt  ft_sp  position  x_num_dogs  Winner_actual  Top3_actual  position_random  Winner_random  Top3_random  \
0        0        0          0       0         0         0          0      0         0      0         0           0              0            0                0              0            0

   position_fasttrack  Winner_fastrack  Top3_fastrack  y_pos  x_dist  x_races_tot  x_no_prev_races  x_speed_prev  x_speed_avg  x_speed_min  x_speed_max  x_speed_range  x_speed_std  G5  G4  G3  G2  \
0                   0                0              0      0       0            0                0             0            0            0            0              0            0   0   0   0   0

   G1  Gmix  Gmas  Gmai  Gh  Gres  Gnov  Gsp  Gfin  RaceGrade_H1
0   0     0     0     0   0     0     0    0     0             0

In [14]:

#keep_cols_for_export = ['@id_DOG', 'DogName', '@id_RACE','RaceName','Track','RaceGrade','Distance','TrainerName','RunTime','Place','x_races_tot']

# 'TrainerName', 'Track' have been dummified
#cols_to_keep = ['@id_DOG', 'DogName', 'y_runtime', 'RaceId', '@id_RACE', 'position', 'ft_sp', 'x_num_dogs', 'Top3_actual', 'position_random', 'position_fasttrack', 'Winner_fastrack', 'Top3_fastrack', 'Winner_actual', 'Winner_random', 'Top3_random']

cols_for_drop = []

#'Event_Dt', 

todaydt = datetime.now().date()
exp_fname = f'modeling_base_{todaydt}.csv'

exp_ds = df_base1.drop(columns = cols_for_drop)

In [15]:

exp_ds.head()

,@id_DOG,DogName,y_runtime,RaceId,@id_RACE,Distance,RaceGrade,Track,Event_Dt,ft_sp,position,x_num_dogs,Winner_actual,Top3_actual,position_random,Winner_random,Top3_random,position_fasttrack,Winner_fastrack,Top3_fastrack,y_pos,x_dist,x_races_tot,x_no_prev_races,x_speed_prev,x_speed_avg,x_speed_min,x_speed_max,x_speed_range,x_speed_std,G5,G4,G3,G2,G1,Gmix,Gmas,Gmai,Gh,Gres,Gnov,Gsp,Gfin,RaceGrade_H1
0,108390981,DOLLY DOES IT,26.43,626271182,626271182,452m,Mixed 4/5,Devonport,2021-01-05,11.0,4,8,0,0,2.0,0,1,5.0,0,0,4,452,0,1,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0,0,0,0,0,1,0,0,0,0,0,0,0,Mixed
1,108390981,DOLLY DOES IT,26.40,629797242,629797242,452m,Grade 5,Devonport,2021-01-12,7.0,5,7,0,0,7.0,0,0,5.0,0,0,5,452,1,0,17101.778282,17101.778282,17101.778282,17101.778282,0.000000,0.000000,1,0,0,0,0,0,0,0,0,0,0,0,0,Grade 5
2,108390981,DOLLY DOES IT,26.20,629797513,629797513,452m,Grade 5,Devonport,2021-01-19,7.0,1,7,1,1,5.0,0,0,4.0,0,0,1,452,2,0,17121.212121,17111.495202,17101.778282,17121.212121,19.433839,13.741799,1,0,0,0,0,0,0,0,0,0,0,0,0,Grade 5
3,108390981,DOLLY DOES IT,26.48,638810808,638810808,452m,Mixed 4/5 Heat,Devonport,2021-02-16,7.0,7,8,0,0,1.0,1,1,4.0,0,0,7,452,3,0,17251.908397,17158.299600,17101.778282,17251.908397,150.130115,81.647864,0,0,0,0,0,1,0,0,1,0,0,0,0,Mixed
4,108390981,DOLLY DOES IT,26.91,643554706,643554706,452m,Grade 4,Devonport,2021-03-02,91.0,8,8,0,0,4.0,0,0,8.0,0,0,8,452,4,0,17069.486405,17136.096301,17069.486405,17251.908397,182.421992,80.101155,0,1,0,0,0,0,0,0,0,0,0,0,0,Grade 4

In [16]:

exp_ds.describe()

,@id_DOG,y_runtime,RaceId,@id_RACE,ft_sp,position,x_num_dogs,Winner_actual,Top3_actual,position_random,Winner_random,Top3_random,position_fasttrack,Winner_fastrack,Top3_fastrack,y_pos,x_dist,x_races_tot,x_no_prev_races,x_speed_prev,x_speed_avg,x_speed_min,x_speed_max,x_speed_range,x_speed_std,G5,G4,G3,G2,G1,Gmix,Gmas,Gmai,Gh,Gres,Gnov,Gsp,Gfin
count,5.415520e+05,541552.000000,5.415520e+05,5.415520e+05,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000,541552.000000
mean,4.525647e+08,24.427979,7.292605e+08,7.292605e+08,16.917818,4.150733,7.305492,0.140127,0.419843,4.152746,0.139857,0.419435,4.013938,0.145510,0.437633,4.150733,417.353562,18.734123,0.049223,16258.984439,16372.453807,15870.525764,16780.460082,909.891907,258.242292,0.401710,0.014992,0.003147,0.001078,0.004627,0.173540,0.021322,0.151780,0.103178,0.053805,0.037082,0.032721,0.042683
std,1.121930e+08,4.983891,5.831714e+07,5.831714e+07,20.995473,2.160054,0.950365,0.347119,0.493534,2.159921,0.346839,0.493467,2.088645,0.352614,0.496096,2.160054,83.856726,16.097282,0.216334,3723.162924,3460.682737,3376.122418,3576.492040,705.188284,201.697242,0.490244,0.121521,0.056006,0.032821,0.067868,0.378714,0.144456,0.358808,0.304191,0.225632,0.188964,0.177905,0.202141
min,1.083910e+08,10.000000,6.238619e+08,6.238619e+08,0.260000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,259.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.836042e+08,20.550000,6.802578e+08,6.802578e+08,4.200000,2.000000,7.000000,0.000000,0.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,2.000000,350.000000,6.000000,0.000000,16795.865633,16881.052752,16306.695464,17237.442922,568.752099,186.539074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.517679e+08,23.540000,7.293859e+08,7.293859e+08,8.700000,4.000000,8.000000,0.000000,0.000000,4.000000,0.000000,0.000000,4.000000,0.000000,0.000000,4.000000,400.000000,15.000000,0.000000,17084.890550,17102.524362,16601.453326,17513.513514,881.521254,250.024868,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.271657e+08,27.190000,7.792436e+08,7.792436e+08,20.600000,6.000000,8.000000,0.000000,1.000000,6.000000,0.000000,1.000000,6.000000,0.000000,1.000000,6.000000,461.000000,28.000000,0.000000,17347.670251,17287.706370,16842.105263,17747.193046,1177.824156,318.220158,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.145360e+09,396.120000,8.292517e+08,8.292517e+08,999.990000,8.000000,8.000000,1.000000,1.000000,8.000000,1.000000,1.000000,8.000000,1.000000,1.000000,8.000000,732.000000,126.000000,1.000000,40200.000000,40200.000000,40200.000000,40200.000000,23978.625954,16614.431948,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:

exp_ds.to_csv(f'{fileloc}/{exp_fname}', index = False)

In [18]:

print("THE END")

THE END